version: '3.1'

services:
  image-repo:
    image: registry
    volumes:
      - registry:/var/lib/registry
    ports:
      - "55000:5000"
    restart: unless-stopped

volumes:
  registry:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/mycloud/Work/DockerRegistry'
