version: '3.3'

services:
  generator:
    image: image-repo:55000/generator:ci-${GENERATOR_BUILD_NUMBER-37}
    environment:
      MAILSERVER__HOST: 192.168.0.24
      MAILSERVER__PORT: 1025
  proxy:
    image: nginx
    ports:
      - ${GENERATOR_PORT-80}:80
    configs:
      - source: site.conf
        target: /etc/nginx/conf.d/default.conf

configs:
  site.conf:
    file: ./site.conf
